apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    type: local 
spec:
  storageClassName: cssp
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cssp"
