apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      run: httpd
    name: httpd
spec:
   replicas: 2
   selector:
     matchLabels:
         run: httpd
   template:
      metadata:
        labels:
          run: httpd
      spec:
        containers:
           - image: httpd
             name:  httpd
        nodeSelector:
           server: "kubernode"
