apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: name.first
    - name: LASTNAME
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: name.last
